sudo: required
language: python
python:
- "2.7"
addons:
  apt:
    packages:
    - docker-ce
    - bash
    - coreutils
branches:
  only:
  - master
install:
- git remote -v
script:
- "bash ./kubeadm_components.sh"
before_install:
- sudo apt-get -y install bash
- sudo apt-get -y install coreutils
- mkdir -p ~/.docker
- mkdir -p ~/.ssh
- aes-256-cbc -K $encrypted_00ad4453bff4_key -iv $encrypted_00ad4453bff4_iv -in certs/config.tar.gz.enc -out config.tar.gz -d
- tar xf config.tar.gz -C ~
- rm -rf config.tar.gz
- mv ~/id_rsa ~/.ssh/id_rsa
- mv ~/config.json ~/.docker/config.json
- chmod 600 ~/.ssh/id_rsa
- chmod 600 ~/.docker/config.json
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
